using System;
using System.Linq;

namespace Mtf.Network.Port
{
    public class PortInfoProvider
    {
        private static readonly PortProperties[] WellKnownPorts = {
            new PortProperties (0, Protocol.TcpOrUdp, "", "", "Reserved"),
            new PortProperties (1, Protocol.TcpOrUdp, "tcpmux", "", "TCP Port Service Multiplexer"),
            new PortProperties (2, Protocol.TcpOrUdp, "compressnet", "", "Management Utility"),
            new PortProperties (3, Protocol.TcpOrUdp, "compressnet", "", "Compression Process"),
            new PortProperties (4, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (5, Protocol.TcpOrUdp, "rje", "", "Remote Job Entry"),
            new PortProperties (6, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (7, Protocol.TcpOrUdp, "echo", "", "Echo"),
            new PortProperties (8, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (9, Protocol.TcpOrUdp, "discard", "sink null", "Discard"),
            new PortProperties (10, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (11, Protocol.TcpOrUdp, "systat", "", "Active Users"),
            new PortProperties (12, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (13, Protocol.TcpOrUdp, "daytime", "", "Daytime"),
            new PortProperties (14, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (15, Protocol.TcpOrUdp, "", "", "Unassigned [TCP was netstat]"),
            new PortProperties (16, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (17, Protocol.TcpOrUdp, "qotd", "quote", "Quote of the day"),
            new PortProperties (18, Protocol.TcpOrUdp, "msp", "", "Message Send Protocol"),
            new PortProperties (19, Protocol.TcpOrUdp, "chargen", "ttytst source", "Character generator"),
            new PortProperties (20, Protocol.TcpOrUdp, "ftp-data", "", "File Transfer [Default Data]"),
            new PortProperties (21, Protocol.TcpOrUdp, "ftp", "", "File Transfer [Control]"),
            new PortProperties (22, Protocol.TcpOrUdp, "ssh", "", "Unassigned [SSH Remote Login Protocol]"),
            new PortProperties (23, Protocol.TcpOrUdp, "telnet", "", "Telnet"),
            new PortProperties (24, Protocol.TcpOrUdp, "", "", "any private mail system"),
            new PortProperties (25, Protocol.TcpOrUdp, "smtp", "mail", "Simple Mail Transfer"),
            new PortProperties (26, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (27, Protocol.TcpOrUdp, "nsw-fe", "", "NSW User System FE"),
            new PortProperties (28, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (29, Protocol.TcpOrUdp, "msg-icp", "", "MSG ICP"),
            new PortProperties (30, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (31, Protocol.TcpOrUdp, "msg-auth", "", "MSG Authentication"),
            new PortProperties (32, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (33, Protocol.TcpOrUdp, "dsp", "", "Display Support Protocol"),
            new PortProperties (34, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (35, Protocol.TcpOrUdp, "", "", "any private printer server"),
            new PortProperties (36, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (37, Protocol.TcpOrUdp, "time", "", "Time"),
            new PortProperties (38, Protocol.TcpOrUdp, "rap", "", "Resource Access Protocol"),
            new PortProperties (39, Protocol.TcpOrUdp, "rlp", "resource", "Resource Location Protocol"),
            new PortProperties (40, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (41, Protocol.TcpOrUdp, "graphics", "", "Graphics"),
            new PortProperties (42, Protocol.TcpOrUdp, "nameserver", "name", "Host Name Server"),
            new PortProperties (43, Protocol.TcpOrUdp, "nicname", "whois", "Who Is"),
            new PortProperties (44, Protocol.TcpOrUdp, "mpm-flags", "", "MPM FLAGS Protocol"),
            new PortProperties (45, Protocol.TcpOrUdp, "mpm", "", "Message Processing Module [recv]"),
            new PortProperties (46, Protocol.TcpOrUdp, "mpm-snd", "", "MPM [default send]"),
            new PortProperties (47, Protocol.TcpOrUdp, "ni-ftp", "", "NI FTP"),
            new PortProperties (48, Protocol.TcpOrUdp, "auditd", "", "Digital Audit Daemon"),
            new PortProperties (49, Protocol.TcpOrUdp, "login", "", "Login Host Protocol"),
            new PortProperties (50, Protocol.TcpOrUdp, "re-mail-ck", "", "Remote Mail Checking Protocol"),
            new PortProperties (51, Protocol.TcpOrUdp, "la-maint", "", "IMP Logical Address Maintenance"),
            new PortProperties (52, Protocol.TcpOrUdp, "xns-time", "", "XNS Time Protocol"),
            new PortProperties (53, Protocol.TcpOrUdp, "domain", "", "Domain Name"),
            new PortProperties (54, Protocol.TcpOrUdp, "xns-ch", "", "XNS Clearinghouse"),
            new PortProperties (55, Protocol.TcpOrUdp, "isi-gl", "", "ISI Graphics Language"),
            new PortProperties (56, Protocol.TcpOrUdp, "xns-auth", "", "XNS Authentication"),
            new PortProperties (57, Protocol.TcpOrUdp, "", "", "any private terminal access"),
            new PortProperties (58, Protocol.TcpOrUdp, "xns-mail", "", "XNS Mail"),
            new PortProperties (59, Protocol.TcpOrUdp, "", "", "any private file service"),
            new PortProperties (60, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (61, Protocol.TcpOrUdp, "ni-mail", "", "NI MAIL"),
            new PortProperties (62, Protocol.TcpOrUdp, "acas", "", "ACA Services"),
            new PortProperties (63, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (64, Protocol.TcpOrUdp, "covia", "", "Communications Integrator (CI)"),
            new PortProperties (65, Protocol.TcpOrUdp, "tacacs-ds", "", "TACACS-Database Service"),
            new PortProperties (66, Protocol.TcpOrUdp, "sql*net", "", "Oracle SQL*NET"),
            new PortProperties (67, Protocol.TcpOrUdp, "bootps", "", "Bootstrap Protocol Server"),
            new PortProperties (68, Protocol.TcpOrUdp, "bootpc", "", "Bootstrap Protocol Client"),
            new PortProperties (69, Protocol.TcpOrUdp, "tftp", "", "Trivial File Transfer"),
            new PortProperties (70, Protocol.TcpOrUdp, "gopher", "", "Gopher"),
            new PortProperties (71, Protocol.TcpOrUdp, "netrjs-1", "", "Remote Job Service"),
            new PortProperties (72, Protocol.TcpOrUdp, "netrjs-2", "", "Remote Job Service"),
            new PortProperties (73, Protocol.TcpOrUdp, "netrjs-3", "", "Remote Job Service"),
            new PortProperties (74, Protocol.TcpOrUdp, "netrjs-4", "", "Remote Job Service"),
            new PortProperties (75, Protocol.TcpOrUdp, "", "", "any private dial out service"),
            new PortProperties (76, Protocol.TcpOrUdp, "deos", "", "Distributed External Object Store"),
            new PortProperties (77, Protocol.TcpOrUdp, "", "", "any private RJE service"),
            new PortProperties (78, Protocol.TcpOrUdp, "vettcp", "", "vettcp"),
            new PortProperties (79, Protocol.TcpOrUdp, "finger", "", "Finger"),
            new PortProperties (80, Protocol.TcpOrUdp, "www-http", "http", "World Wide Web HTTP", "SYN flood"),
            new PortProperties (81, Protocol.TcpOrUdp, "hosts2-ns", "", "HOSTS2 Name Server"),
            new PortProperties (82, Protocol.TcpOrUdp, "xfer", "", "XFER Utility"),
            new PortProperties (83, Protocol.TcpOrUdp, "mit-ml-dev", "", "MIT ML Device"),
            new PortProperties (84, Protocol.TcpOrUdp, "ctf", "", "Common Trace Facility"),
            new PortProperties (85, Protocol.TcpOrUdp, "mit-ml-dev", "", "MIT ML Device"),
            new PortProperties (86, Protocol.TcpOrUdp, "mfcobol", "", "Micro Focus Cobol"),
            new PortProperties (87, Protocol.TcpOrUdp, "", "", "any private terminal link"),
            new PortProperties (88, Protocol.TcpOrUdp, "kerberos", "krb5", "Kerberos"),
            new PortProperties (89, Protocol.TcpOrUdp, "su-mit-tg", "", "SU/MIT Telnet Gateway"),
            new PortProperties (90, Protocol.TcpOrUdp, "dnsix", "", "DNSIX Securit Attribute Token Map"),
            new PortProperties (91, Protocol.TcpOrUdp, "mit-dov", "", "MIT Dover Spooler"),
            new PortProperties (92, Protocol.TcpOrUdp, "npp", "", "Network Printing Protocol"),
            new PortProperties (93, Protocol.TcpOrUdp, "dcp", "", "Device Control Protocol"),
            new PortProperties (94, Protocol.TcpOrUdp, "objcall", "", "Tivoli Object Dispatcher"),
            new PortProperties (95, Protocol.TcpOrUdp, "supdup", "", "SUPDUP"),
            new PortProperties (96, Protocol.TcpOrUdp, "dixie", "", "DIXIE Protocol Specification"),
            new PortProperties (97, Protocol.TcpOrUdp, "swift-rvf", "", "Swift Remote Virtual File Protocol"),
            new PortProperties (98, Protocol.TcpOrUdp, "tacnews", "", "TAC News"),
            new PortProperties (99, Protocol.TcpOrUdp, "metagram", "", "Metagram Relay"),
            new PortProperties (100, Protocol.Tcp, "newacct", "", "[unauthorized use]"),
            new PortProperties (101, Protocol.TcpOrUdp, "hostname", "hostnames", "NIC Host Name Server"),
            new PortProperties (102, Protocol.TcpOrUdp, "iso-tsap", "", "ISO-TSAP"),
            new PortProperties (103, Protocol.TcpOrUdp, "gppitnp", "", "Genesis Point-to-Point Trans Net"),
            new PortProperties (104, Protocol.TcpOrUdp, "acr-name", "", "ACR-NEMA Digital Imag. & Comm. 300"),
            new PortProperties (105, Protocol.TcpOrUdp, "csnet-ns", "", "Mailbox Name Nameserver"),
            new PortProperties (106, Protocol.TcpOrUdp, "3com-tsmux", "", "3COM-TSMUX"),
            new PortProperties (107, Protocol.TcpOrUdp, "rtelnet", "", "Remote Telnet Service"),
            new PortProperties (108, Protocol.TcpOrUdp, "snagas", "", "SNA Gateway Access Server"),
            new PortProperties (109, Protocol.TcpOrUdp, "pop2", "postoffice", "Post Office Protocol - Version 2"),
            new PortProperties (110, Protocol.TcpOrUdp, "pop3", "postoffice", "Post Office Protocol - Version 3"),
            new PortProperties (111, Protocol.TcpOrUdp, "sunrpc", "rpcbind portmap", "SUN Remote Procedure Call"),
            new PortProperties (112, Protocol.TcpOrUdp, "mcidas", "", "McIDAS Data Transmittion Protocol"),
            new PortProperties (113, Protocol.TcpOrUdp, "auth", "ident tap", "Authentication Service"),
            new PortProperties (114, Protocol.TcpOrUdp, "audionews", "", "Audio News Multicast"),
            new PortProperties (115, Protocol.TcpOrUdp, "sftp", "", "Simple File Transfer Protocol"),
            new PortProperties (116, Protocol.TcpOrUdp, "ansanotify", "", "ANSA REX Notify"),
            new PortProperties (117, Protocol.TcpOrUdp, "uucp-path", "", "UUCP Path Service"),
            new PortProperties (118, Protocol.TcpOrUdp, "sqlserv", "", "SQL Services"),
            new PortProperties (119, Protocol.TcpOrUdp, "nntp", "usenet", "Network News Transfer Protocol"),
            new PortProperties (120, Protocol.TcpOrUdp, "cfdptkt", "", "CFDPTKT"),
            new PortProperties (121, Protocol.TcpOrUdp, "erpc", "", "Encore Expedited Remote Pro.Call"),
            new PortProperties (122, Protocol.TcpOrUdp, "smakynet", "", "SMAKYNET"),
            new PortProperties (123, Protocol.TcpOrUdp, "ntp", "", "Network Time Protocol"),
            new PortProperties (124, Protocol.TcpOrUdp, "ansatrader", "", "ANSA REX Trader"),
            new PortProperties (125, Protocol.TcpOrUdp, "locus-map", "", "Locus PC-Interface Net Map Ser"),
            new PortProperties (126, Protocol.TcpOrUdp, "unitary", "", "Unisys Unitary Login"),
            new PortProperties (127, Protocol.TcpOrUdp, "locus-con", "", "Locus PC-Interface Conn Server"),
            new PortProperties (128, Protocol.TcpOrUdp, "gss-xlicen", "", "GSS X License Verification"),
            new PortProperties (129, Protocol.TcpOrUdp, "pwdgen", "", "Password Generator Protocol"),
            new PortProperties (130, Protocol.TcpOrUdp, "cisco-fna", "", "cisco FNATIVE"),
            new PortProperties (131, Protocol.TcpOrUdp, "cisco-tna", "", "cisco TNATIVE"),
            new PortProperties (132, Protocol.TcpOrUdp, "cisco-sys", "", "cisco SYSMAINT"),
            new PortProperties (133, Protocol.TcpOrUdp, "statsrv", "", "Statistics Service"),
            new PortProperties (134, Protocol.TcpOrUdp, "ingres-net", "", "INGRES-NET Service"),
            new PortProperties (135, Protocol.TcpOrUdp, "epmap", "loc-srv", "DCE endpoint resolution"),
            new PortProperties (136, Protocol.TcpOrUdp, "profile", "", "PROFILE Naming System"),
            new PortProperties (137, Protocol.TcpOrUdp, "netbios-ns", "nbname", "NETBIOS Name Service"),
            new PortProperties (138, Protocol.TcpOrUdp, "netbios-dgm", "nbdatagram", "NETBIOS Datagram Service"),
            new PortProperties (139, Protocol.TcpOrUdp, "netbios-ssn", "nbsession", "NETBIOS Session Service"),
            new PortProperties (140, Protocol.TcpOrUdp, "emfis-data", "", "EMFIS Data Service"),
            new PortProperties (141, Protocol.TcpOrUdp, "emfis-cntl", "", "EMFIS Control Service"),
            new PortProperties (142, Protocol.TcpOrUdp, "bl-idm", "", "Britton-Lee IDM"),
            new PortProperties (143, Protocol.TcpOrUdp, "imap2", "imap, imap4", "Interim Mail Access Protocol v2"),
            new PortProperties (144, Protocol.TcpOrUdp, "news", "", "NewS"),
            new PortProperties (145, Protocol.TcpOrUdp, "uaac", "", "UAAC Protocol"),
            new PortProperties (146, Protocol.TcpOrUdp, "iso-tp0", "", "ISO-IP0"),
            new PortProperties (147, Protocol.TcpOrUdp, "iso-ip", "", "ISO-IP"),
            new PortProperties (148, Protocol.TcpOrUdp, "cronus", "", "CRONUS-SUPPORT"),
            new PortProperties (149, Protocol.TcpOrUdp, "aed-512", "", "AED Emulation Service"),
            new PortProperties (150, Protocol.TcpOrUdp, "sql-net", "", "SQL-NET"),
            new PortProperties (151, Protocol.TcpOrUdp, "hems", "", "HEMS"),
            new PortProperties (152, Protocol.TcpOrUdp, "bftp", "", "Background File Transfer Program"),
            new PortProperties (153, Protocol.TcpOrUdp, "sgmp", "", "SGMP"),
            new PortProperties (154, Protocol.TcpOrUdp, "netsc-prod", "", "NETSC"),
            new PortProperties (155, Protocol.TcpOrUdp, "netsc-dev", "", "NETSC"),
            new PortProperties (156, Protocol.TcpOrUdp, "sqlsrv", "", "SQL Service"),
            new PortProperties (157, Protocol.TcpOrUdp, "knet-cmp", "", "KNET/VM Command/Message Protocol"),
            new PortProperties (158, Protocol.TcpOrUdp, "pcmail-srv", "repository", "PC Mail Server"),
            new PortProperties (159, Protocol.TcpOrUdp, "nss-routing", "", "NSS-Routing"),
            new PortProperties (160, Protocol.TcpOrUdp, "sgmp-traps", "", "SGMP-TRAPS"),
            new PortProperties (161, Protocol.TcpOrUdp, "snmp", "snmp", "SNMP"),
            new PortProperties (162, Protocol.TcpOrUdp, "snmptrap", "snmp-trap", "SNMP TRAP"),
            new PortProperties (163, Protocol.TcpOrUdp, "cmip-man", "", "CMIP/TCP Manager"),
            new PortProperties (164, Protocol.TcpOrUdp, "cmip-agent", "", "CMIP/TCP Agent"),
            new PortProperties (165, Protocol.TcpOrUdp, "xns-courier", "", "Xerox"),
            new PortProperties (166, Protocol.TcpOrUdp, "s-net", "", "Sirius Systems"),
            new PortProperties (167, Protocol.TcpOrUdp, "namp", "", "NAMP"),
            new PortProperties (168, Protocol.TcpOrUdp, "rsvd", "", "RSVD"),
            new PortProperties (169, Protocol.TcpOrUdp, "send", "", "SEND"),
            new PortProperties (170, Protocol.TcpOrUdp, "print-srv", "", "Network PostScript"),
            new PortProperties (171, Protocol.TcpOrUdp, "multiplex", "", "Network Innovations Multiplex"),
            new PortProperties (172, Protocol.TcpOrUdp, "cl/1", "", "Network Innovations CL/1"),
            new PortProperties (173, Protocol.TcpOrUdp, "xyplex-mux", "", "Xyplex"),
            new PortProperties (174, Protocol.TcpOrUdp, "mailq", "", "MAILQ"),
            new PortProperties (175, Protocol.TcpOrUdp, "vmnet", "", "VMNET"),
            new PortProperties (176, Protocol.TcpOrUdp, "genrad-mux", "", "GENRAD-MUX"),
            new PortProperties (177, Protocol.TcpOrUdp, "xdmcp", "", "X Display Manager Control Protocol"),
            new PortProperties (178, Protocol.TcpOrUdp, "NextStep", "", "NextStep Window Server"),
            new PortProperties (179, Protocol.TcpOrUdp, "bgp", "", "Border Gateway Protocol"),
            new PortProperties (180, Protocol.TcpOrUdp, "ris", "", "Intergraph"),
            new PortProperties (181, Protocol.TcpOrUdp, "unify", "", "Unify"),
            new PortProperties (182, Protocol.TcpOrUdp, "audit", "", "Unisys Audit SITP"),
            new PortProperties (183, Protocol.TcpOrUdp, "ocbinder", "", "OCBinder"),
            new PortProperties (184, Protocol.TcpOrUdp, "ocserver", "", "OCServer"),
            new PortProperties (185, Protocol.TcpOrUdp, "remote-kis", "", "Remote-KIS"),
            new PortProperties (186, Protocol.TcpOrUdp, "kis", "", "KIS Protocol"),
            new PortProperties (187, Protocol.TcpOrUdp, "aci", "", "Application Communication Interface"),
            new PortProperties (188, Protocol.TcpOrUdp, "mumps", "", "Plus Five's MUMPS"),
            new PortProperties (189, Protocol.TcpOrUdp, "qft", "", "Queued File Transport"),
            new PortProperties (190, Protocol.TcpOrUdp, "gacp", "", "Gateway Access Control Protocol"),
            new PortProperties (191, Protocol.TcpOrUdp, "prospero", "", "Prospero Directory Service"),
            new PortProperties (192, Protocol.TcpOrUdp, "osu-nms", "", "OSU Network Monitoring System"),
            new PortProperties (193, Protocol.TcpOrUdp, "srmp", "", "Spider Remote Monitoring Protocol"),
            new PortProperties (194, Protocol.TcpOrUdp, "irc", "", "Internet Relay Chat Protocol"),
            new PortProperties (195, Protocol.TcpOrUdp, "dn6-nlm-aud", "", "DNSIX Network Level Module Audit"),
            new PortProperties (196, Protocol.TcpOrUdp, "dn6-smm-red", "", "DNSIX Session Mgt Module Audit Redir"),
            new PortProperties (197, Protocol.TcpOrUdp, "dls", "", "Directory Location Service"),
            new PortProperties (198, Protocol.TcpOrUdp, "dls-mon", "", "Directory Location Service Monitor"),
            new PortProperties (199, Protocol.TcpOrUdp, "smux", "", "SMUX"),
            new PortProperties (200, Protocol.TcpOrUdp, "src", "", "IBM System Resource Controller"),
            new PortProperties (201, Protocol.TcpOrUdp, "at-rtmp", "", "AppleTalk Routing Maintenance"),
            new PortProperties (202, Protocol.TcpOrUdp, "at-nbp", "", "AppleTalk Name Binding"),
            new PortProperties (203, Protocol.TcpOrUdp, "at-3", "", "AppleTalk Unused"),
            new PortProperties (204, Protocol.TcpOrUdp, "at-echo", "", "AppleTalk Echo"),
            new PortProperties (205, Protocol.TcpOrUdp, "at-5", "", "AppleTalk Unused"),
            new PortProperties (206, Protocol.TcpOrUdp, "at-zis", "", "AppleTalk Zone Information"),
            new PortProperties (207, Protocol.TcpOrUdp, "at-7", "", "AppleTalk Unused"),
            new PortProperties (208, Protocol.TcpOrUdp, "at-8", "", "AppleTalk Unused"),
            new PortProperties (209, Protocol.TcpOrUdp, "tam", "", "Trivial Authenticated Mail Protocol"),
            new PortProperties (210, Protocol.TcpOrUdp, "z39.50", "", "ANSI Z39.50"),
            new PortProperties (211, Protocol.TcpOrUdp, "914c/g", "", "Texas Instruments 914C/G Terminal"),
            new PortProperties (212, Protocol.TcpOrUdp, "anet", "", "ATEXSSTR"),
            new PortProperties (213, Protocol.TcpOrUdp, "ipx", "", "IPX"),
            new PortProperties (214, Protocol.TcpOrUdp, "vmpwscs", "", "VM PWSCS"),
            new PortProperties (215, Protocol.TcpOrUdp, "softpc", "", "Insignia Solutions"),
            new PortProperties (216, Protocol.TcpOrUdp, "atls", "", "Access Technology License Server"),
            new PortProperties (217, Protocol.TcpOrUdp, "dbase", "", "dBASE Unix"),
            new PortProperties (218, Protocol.TcpOrUdp, "mpp", "", "Netix Message Posting Protocol"),
            new PortProperties (219, Protocol.TcpOrUdp, "uarps", "", "Unisys ARPs"),
            new PortProperties (220, Protocol.TcpOrUdp, "imap3", "", "Interactive Mail Access Protocol v3"),
            new PortProperties (221, Protocol.TcpOrUdp, "fln-spx", "", "Berkeley rlogind with SPX auth"),
            new PortProperties (222, Protocol.TcpOrUdp, "rsh-spx", "", "Berkeley rshd with SPX auth"),
            new PortProperties (223, Protocol.TcpOrUdp, "cdc", "", "Certificate Distribution Center"),
            new PortProperties (243, Protocol.TcpOrUdp, "sur-meas", "", "Survey Measurement"),
            new PortProperties (245, Protocol.TcpOrUdp, "link", "", "LINK"),
            new PortProperties (246, Protocol.TcpOrUdp, "dsp3270", "", "Display Systems Protocol"),
            new PortProperties (344, Protocol.TcpOrUdp, "pdap", "", "Prospero Data Access Protocol"),
            new PortProperties (345, Protocol.TcpOrUdp, "pawserv", "", "Perf Analysis Workbench"),
            new PortProperties (346, Protocol.TcpOrUdp, "zserv", "", "Zebra server"),
            new PortProperties (347, Protocol.TcpOrUdp, "fatserv", "", "Fatmen Server"),
            new PortProperties (348, Protocol.TcpOrUdp, "csi-sgwp", "", "Cabletron Management Protocol"),
            new PortProperties (371, Protocol.TcpOrUdp, "clearcase", "", "Clearcase"),
            new PortProperties (372, Protocol.TcpOrUdp, "ulistserv", "", "Unix Listserv"),
            new PortProperties (373, Protocol.TcpOrUdp, "legent-1", "", "Legent Corporation"),
            new PortProperties (374, Protocol.TcpOrUdp, "legent-2", "", "Legent Corporation"),
            new PortProperties (375, Protocol.TcpOrUdp, "hassle", "", "Hassle"),
            new PortProperties (376, Protocol.TcpOrUdp, "nip", "", "Amiga Envoy Network Inquiry Proto"),
            new PortProperties (377, Protocol.TcpOrUdp, "tnETOS", "", "NEC Corporation"),
            new PortProperties (378, Protocol.TcpOrUdp, "dsETOS", "", "NEC Corporation"),
            new PortProperties (379, Protocol.TcpOrUdp, "is99c", "", "TIA/EIA/IS-modem client"),
            new PortProperties (380, Protocol.TcpOrUdp, "is99s", "", "TIA/EIA/IS-modem server"),
            new PortProperties (381, Protocol.TcpOrUdp, "hp-collector", "", "hp performance data collector"),
            new PortProperties (382, Protocol.TcpOrUdp, "hp-managed-node", "", "hp performance data managed node"),
            new PortProperties (383, Protocol.TcpOrUdp, "hp-alarm-mgr", "", "hp performance data alarm manager"),
            new PortProperties (384, Protocol.TcpOrUdp, "arns", "", "A Remote Network Server System"),
            new PortProperties (385, Protocol.Tcp, "ibm-app", "", "IBM Application"),
            new PortProperties (385, Protocol.Tcp, "ibm-app", "", "IBM Application"),
            new PortProperties (386, Protocol.TcpOrUdp, "asa", "", "ASA Message Router Object Def."),
            new PortProperties (387, Protocol.TcpOrUdp, "aurp", "", "Appletalk Update-Based Routing Pro."),
            new PortProperties (388, Protocol.TcpOrUdp, "unidata-ldm", "", "Unidata LDM Version 4"),
            new PortProperties (389, Protocol.TcpOrUdp, "ldap", "", "Lightweight Directory Access Protocol"),
            new PortProperties (390, Protocol.TcpOrUdp, "uis", "", "UIS"),
            new PortProperties (391, Protocol.TcpOrUdp, "synotics-relay", "", "SynOptics SNMP Relay Port"),
            new PortProperties (392, Protocol.TcpOrUdp, "synotics-broker", "", "SynOptics Port Broker Port"),
            new PortProperties (393, Protocol.TcpOrUdp, "dis", "", "Data Interpretation System"),
            new PortProperties (394, Protocol.TcpOrUdp, "embl-ndt", "", "EMBL Nucleic Data Transfer"),
            new PortProperties (395, Protocol.TcpOrUdp, "netcp", "", "NETscout Control Protocol"),
            new PortProperties (396, Protocol.TcpOrUdp, "netware-ip", "", "Novell Netware over IP"),
            new PortProperties (397, Protocol.TcpOrUdp, "mptn", "", "Multi Protocol Trans. Net."),
            new PortProperties (398, Protocol.TcpOrUdp, "kryptolan", "", "Kryptolan"),
            new PortProperties (400, Protocol.TcpOrUdp, "work-sol", "", "Workstation Solutions"),
            new PortProperties (401, Protocol.TcpOrUdp, "ups", "", "Uninterruptible Power Supply"),
            new PortProperties (402, Protocol.TcpOrUdp, "genie", "", "Genie Protocol"),
            new PortProperties (403, Protocol.TcpOrUdp, "decap", "", "decap"),
            new PortProperties (404, Protocol.TcpOrUdp, "nced", "", "nced"),
            new PortProperties (405, Protocol.TcpOrUdp, "ncld", "", "ncld"),
            new PortProperties (406, Protocol.TcpOrUdp, "imsp", "", "Interactive Mail Support Protocol"),
            new PortProperties (407, Protocol.TcpOrUdp, "timbuktu", "", "Timbuktu"),
            new PortProperties (408, Protocol.TcpOrUdp, "prm-sm", "", "Prospero Resource Manager Sys. Man."),
            new PortProperties (409, Protocol.TcpOrUdp, "prm-nm", "", "Prospero Resource Manager Node Man."),
            new PortProperties (410, Protocol.TcpOrUdp, "decladebug", "", "DECLadebug Remote Debug Protocol"),
            new PortProperties (411, Protocol.TcpOrUdp, "rmt", "", "Remote MT Protocol"),
            new PortProperties (412, Protocol.TcpOrUdp, "synoptics-trap", "", "Trap Convention Port"),
            new PortProperties (413, Protocol.TcpOrUdp, "smsp", "", "SMSP"),
            new PortProperties (414, Protocol.TcpOrUdp, "infoseek", "", "InfoSeek"),
            new PortProperties (415, Protocol.TcpOrUdp, "bnet", "", "BNet"),
            new PortProperties (416, Protocol.TcpOrUdp, "silverplatter", "", "Silverplatter"),
            new PortProperties (417, Protocol.TcpOrUdp, "onmux", "", "Onmux"),
            new PortProperties (418, Protocol.TcpOrUdp, "hyper-g", "", "Hyper-G"),
            new PortProperties (419, Protocol.TcpOrUdp, "ariel1", "", "Ariel"),
            new PortProperties (420, Protocol.TcpOrUdp, "smpte", "", "SMPTE"),
            new PortProperties (421, Protocol.TcpOrUdp, "ariel2", "", "Ariel"),
            new PortProperties (422, Protocol.TcpOrUdp, "ariel3", "", "Ariel"),
            new PortProperties (423, Protocol.TcpOrUdp, "opc-job-start", "", "IBM Operations Planning and Control Start"),
            new PortProperties (424, Protocol.TcpOrUdp, "opc-job-track", "", "IBM Operations Planning and Control Track"),
            new PortProperties (425, Protocol.TcpOrUdp, "icad-el", "", "ICAD"),
            new PortProperties (426, Protocol.TcpOrUdp, "smartsdp", "", "smartsdp"),
            new PortProperties (427, Protocol.TcpOrUdp, "svrloc", "", "Server Location"),
            new PortProperties (428, Protocol.TcpOrUdp, "ocs_cmu", "", "OCS_CMU"),
            new PortProperties (429, Protocol.TcpOrUdp, "ocs_amu", "", "OCS_AMU"),
            new PortProperties (430, Protocol.TcpOrUdp, "utmpsd", "", "UTMPSD"),
            new PortProperties (431, Protocol.TcpOrUdp, "utmpcd", "", "UTMPCD"),
            new PortProperties (432, Protocol.TcpOrUdp, "iasd", "", "IASD"),
            new PortProperties (433, Protocol.TcpOrUdp, "nnsp", "", "NNSP"),
            new PortProperties (434, Protocol.TcpOrUdp, "mobileip-agent", "", "MobileIP-Agent"),
            new PortProperties (435, Protocol.TcpOrUdp, "mobilip-mn", "", "MobilIP-MN"),
            new PortProperties (436, Protocol.TcpOrUdp, "dna-cml", "", "DNA-CML"),
            new PortProperties (437, Protocol.TcpOrUdp, "comscm", "", "comscm"),
            new PortProperties (438, Protocol.TcpOrUdp, "dsfgw", "", "dsfgw"),
            new PortProperties (439, Protocol.TcpOrUdp, "dasp", "", "dasp"),
            new PortProperties (440, Protocol.TcpOrUdp, "sgcp", "", "sgcp"),
            new PortProperties (441, Protocol.TcpOrUdp, "decvms-sysmgt", "", "decvms-sysmgt"),
            new PortProperties (442, Protocol.TcpOrUdp, "cvc_hostd", "", "cvc_hostd"),
            new PortProperties (443, Protocol.TcpOrUdp, "https", "", "https MCom"),
            new PortProperties (444, Protocol.TcpOrUdp, "snpp", "", "Simple Network Paging Protocol"),
            new PortProperties (445, Protocol.TcpOrUdp, "microsoft-ds", "", "Microsoft CIFS"),
            new PortProperties (446, Protocol.TcpOrUdp, "ddm-rdb", "", "DDM-RDB"),
            new PortProperties (447, Protocol.TcpOrUdp, "ddm-dfm", "", "DDM-RFM"),
            new PortProperties (448, Protocol.TcpOrUdp, "ddm-byte", "", "DDM-BYTE"),
            new PortProperties (449, Protocol.TcpOrUdp, "as-servermap", "", "AS Server Mapper"),
            new PortProperties (450, Protocol.TcpOrUdp, "tserver", "", "TServer"),
            new PortProperties (451, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (452, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (453, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (454, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (455, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (456, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (457, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (458, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (459, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (460, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (461, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (462, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (464, Protocol.TcpOrUdp, "kpasswd", "", "Kerberos (v5)"),
            new PortProperties (465, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (466, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (467, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (468, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (469, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (470, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (471, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (472, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (473, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (474, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (475, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (476, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (477, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (478, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (479, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (480, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (481, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (482, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (483, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (484, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (485, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (486, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (487, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (488, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (489, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (490, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (491, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (492, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (493, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (494, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (495, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (496, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (497, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (498, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (500, Protocol.TcpOrUdp, "isakmp", "ike", "Internet Key Exchange (IPSec)"),
            new PortProperties (501, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (502, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (503, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (504, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (505, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (506, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (507, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (508, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (509, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (510, Protocol.TcpOrUdp, "", "", "Unassigned"),
            new PortProperties (512, Protocol.Tcp, "exec", "", "Remote Process Execution"),
            new PortProperties (512, Protocol.Udp, "biff", "comsat", "used by mail system to notify users"),
            new PortProperties (513, Protocol.Tcp, "login", "", "Remote login a la telnet;"),
            new PortProperties (513, Protocol.Udp, "who", "whod", "Database of who's logged on, average load"),
            new PortProperties (514, Protocol.Tcp, "cmd", "", "like exec, but automatic authentication"),
            new PortProperties (514, Protocol.Udp, "syslog"),
            new PortProperties (515, Protocol.TcpOrUdp, "printer", "spooler", "Listens for incoming connections"),
            new PortProperties (517, Protocol.TcpOrUdp, "talk", "", "Establishes TCP Connection - like tenex link"),
            new PortProperties (518, Protocol.TcpOrUdp, "ntalk"),
            new PortProperties (519, Protocol.TcpOrUdp, "utime", "", "unixtime"),
            new PortProperties (520, Protocol.Tcp, "efs", "", "Extended File Name Server"),
            new PortProperties (520, Protocol.Udp, "router", "router routed", "RIPv.1, RIPv.2, local routing process (on site)"),
            new PortProperties (525, Protocol.TcpOrUdp, "timed", "timeserver", "Timeserver"),
            new PortProperties (526, Protocol.TcpOrUdp, "tempo", "newdate", "Newdate"),
            new PortProperties (530, Protocol.TcpOrUdp, "courier", "rpc", "RPC"),
            new PortProperties (531, Protocol.TcpOrUdp, "conference", "chat", "IRC Chat"),
            new PortProperties (532, Protocol.TcpOrUdp, "netnews", "readnews", "Readnews"),
            new PortProperties (533, Protocol.TcpOrUdp, "netwall", "", "For emergency broadcasts"),
            new PortProperties (539, Protocol.TcpOrUdp, "apertus-ldp", "", "Apertus Technologies Load Determination"),
            new PortProperties (540, Protocol.TcpOrUdp, "uucp", "uucpd", "Uucpd"),
            new PortProperties (541, Protocol.TcpOrUdp, "uucp-rlogin", "", "uucp-rlogin"),
            new PortProperties (543, Protocol.TcpOrUdp, "klogin", "", "Kerberos login"),
            new PortProperties (544, Protocol.TcpOrUdp, "kshell", "krcmd", "Kerberos remote shell"),
            new PortProperties (550, Protocol.TcpOrUdp, "new-rwho", "new-who", "New-who"),
            new PortProperties (555, Protocol.TcpOrUdp, "dsf"),
            new PortProperties (556, Protocol.TcpOrUdp, "remotefs", "rfs rfs_server", "rfs server"),
            new PortProperties (560, Protocol.TcpOrUdp, "rmonitor", "rmonitord", "Rmonitor"),
            new PortProperties (561, Protocol.TcpOrUdp, "monitor"),
            new PortProperties (562, Protocol.TcpOrUdp, "chshell", "", "chcmd"),
            new PortProperties (564, Protocol.TcpOrUdp, "9pfs", "", "plan 9 file service"),
            new PortProperties (565, Protocol.TcpOrUdp, "whoami", "", "whoami"),
            new PortProperties (570, Protocol.TcpOrUdp, "meter", "", "demon"),
            new PortProperties (571, Protocol.TcpOrUdp, "meter", "", "udemon"),
            new PortProperties (600, Protocol.TcpOrUdp, "ipcserver", "", "Sun IPC server"),
            new PortProperties (607, Protocol.TcpOrUdp, "nqs", "", "nqs"),
            new PortProperties (606, Protocol.TcpOrUdp, "urm", "", "Cray Unified Resource Manager"),
            new PortProperties (608, Protocol.TcpOrUdp, "sift-uft", "", "Sender-Initiated/Unsolicited File Transfer"),
            new PortProperties (609, Protocol.TcpOrUdp, "npmp-trap", "", "npmp-trap"),
            new PortProperties (610, Protocol.TcpOrUdp, "npmp-local", "", "npmp-local"),
            new PortProperties (611, Protocol.TcpOrUdp, "npmp-gui", "", "npmp-gui"),
            new PortProperties (634, Protocol.TcpOrUdp, "ginad", "", "ginad"),
            new PortProperties (636, Protocol.Tcp, "ldaps", "sldap", "LDAP over TLS/SSL"),
            new PortProperties (666, Protocol.TcpOrUdp, "mdqs"),
            new PortProperties (666, Protocol.Tcp, "doom", "", "doom Id Software"),
            new PortProperties (704, Protocol.TcpOrUdp, "elcsd", "", "errlog copy/server daemon"),
            new PortProperties (709, Protocol.TcpOrUdp, "entrustmanager", "", "EntrustManager"),
            new PortProperties (729, Protocol.TcpOrUdp, "netviewdm1", "", "IBM NetView DM/6Server/Client"),
            new PortProperties (730, Protocol.TcpOrUdp, "netviewdm2", "", "IBM NetView DM/6send/tcp"),
            new PortProperties (731, Protocol.TcpOrUdp, "netviewdm3", "", "IBM NetView DM/6receive/tcp"),
            new PortProperties (741, Protocol.TcpOrUdp, "netgw", "", "netGW"),
            new PortProperties (742, Protocol.TcpOrUdp, "netrcs", "", "Network based Rev. Cont. Sys."),
            new PortProperties (744, Protocol.TcpOrUdp, "flexlm", "", "Flexible License Manager"),
            new PortProperties (747, Protocol.TcpOrUdp, "fujitsu-dev", "", "Fujitsu Device Control"),
            new PortProperties (748, Protocol.TcpOrUdp, "ris-cm", "", "Russell Info Sci Calendar Manager"),
            new PortProperties (749, Protocol.TcpOrUdp, "kerberos-adm", "", "Kerberos Administration"),
            new PortProperties (750, Protocol.Tcp, "rfile"),
            new PortProperties (750, Protocol.Udp, "loadav"),
            new PortProperties (751, Protocol.TcpOrUdp, "pump"),
            new PortProperties (752, Protocol.TcpOrUdp, "qrh"),
            new PortProperties (753, Protocol.TcpOrUdp, "rrh"),
            new PortProperties (754, Protocol.TcpOrUdp, "tell", "", "send"),
            new PortProperties (758, Protocol.TcpOrUdp, "nlogin"),
            new PortProperties (759, Protocol.TcpOrUdp, "con"),
            new PortProperties (760, Protocol.TcpOrUdp, "ns"),
            new PortProperties (761, Protocol.TcpOrUdp, "rxe"),
            new PortProperties (762, Protocol.TcpOrUdp, "quotad"),
            new PortProperties (763, Protocol.TcpOrUdp, "cycleserv"),
            new PortProperties (764, Protocol.TcpOrUdp, "omserv"),
            new PortProperties (765, Protocol.TcpOrUdp, "webster"),
            new PortProperties (767, Protocol.TcpOrUdp, "phonebook", "", "phone"),
            new PortProperties (769, Protocol.TcpOrUdp, "vid"),
            new PortProperties (770, Protocol.TcpOrUdp, "cadlock"),
            new PortProperties (771, Protocol.TcpOrUdp, "rtip"),
            new PortProperties (772, Protocol.TcpOrUdp, "cycleserv2"),
            new PortProperties (773, Protocol.Tcp, "submit"),
            new PortProperties (773, Protocol.Udp, "notify"),
            new PortProperties (774, Protocol.Tcp, "rpasswd"),
            new PortProperties (774, Protocol.Udp, "acmaint_dbd"),
            new PortProperties (775, Protocol.Tcp, "entomb"),
            new PortProperties (775, Protocol.Udp, "acmaint_transd"),
            new PortProperties (776, Protocol.TcpOrUdp, "wpages"),
            new PortProperties (780, Protocol.TcpOrUdp, "wpgs"),
            new PortProperties (786, Protocol.TcpOrUdp, "concert", "", "Concert"),
            new PortProperties (800, Protocol.TcpOrUdp, "mdbs_daemon"),
            new PortProperties (801, Protocol.TcpOrUdp, "device"),
            new PortProperties (996, Protocol.TcpOrUdp, "xtreelic", "", "Central Point Software"),
            new PortProperties (997, Protocol.TcpOrUdp, "maitrd"),
            new PortProperties (998, Protocol.Tcp, "busboy"),
            new PortProperties (998, Protocol.Udp, "puparp"),
            new PortProperties (999, Protocol.Tcp, "garcon"),
            new PortProperties (999, Protocol.Udp, "applix", "", "Applix ac"),
            new PortProperties (999, Protocol.TcpOrUdp, "puprouter"),
            new PortProperties (1000, Protocol.Tcp, "cadlock"),
            new PortProperties (1000, Protocol.Udp, "ock"),
            new PortProperties (1023, Protocol.Tcp, "", "", "Reserved"),
            new PortProperties (1024, Protocol.Udp, "", "", "Reserved"),
            new PortProperties (1024, Protocol.TcpOrUdp, "", "", "Reserved"),
            new PortProperties (1025, Protocol.TcpOrUdp, "blackjack", "", "network blackjack"),
            new PortProperties (1030, Protocol.TcpOrUdp, "iad1", "", "BBN IAD"),
            new PortProperties (1031, Protocol.TcpOrUdp, "iad2", "", "BBN IAD"),
            new PortProperties (1032, Protocol.TcpOrUdp, "iad3", "", "BBN IAD"),
            new PortProperties (1067, Protocol.TcpOrUdp, "instl_boots", "", "Installation Bootstrap Proto. Serv."),
            new PortProperties (1068, Protocol.TcpOrUdp, "instl_bootc", "", "Installation Bootstrap Proto. Cli."),
            new PortProperties (1080, Protocol.TcpOrUdp, "socks", "", "Socks"),
            new PortProperties (1083, Protocol.TcpOrUdp, "ansoft-lm-1", "", "Anasoft License Manager"),
            new PortProperties (1084, Protocol.TcpOrUdp, "ansoft-lm-2", "", "Anasoft License Manager"),
            new PortProperties (1155, Protocol.TcpOrUdp, "nfa", "", "Network File Access"),
            new PortProperties (1222, Protocol.TcpOrUdp, "nerv", "", "SNI R&D network"),
            new PortProperties (1248, Protocol.TcpOrUdp, "hermes"),
            new PortProperties (1346, Protocol.TcpOrUdp, "alta-ana-lm", "", "Alta Analytics License Manager"),
            new PortProperties (1347, Protocol.TcpOrUdp, "bbn-mmc", "", "multi media conferencing"),
            new PortProperties (1348, Protocol.TcpOrUdp, "bbn-mmx", "", "multi media conferencing"),
            new PortProperties (1349, Protocol.TcpOrUdp, "sbook", "", "Registration Network Protocol"),
            new PortProperties (1350, Protocol.TcpOrUdp, "editbench", "", "Registration Network Protocol"),
            new PortProperties (1351, Protocol.TcpOrUdp, "equationbuilder", "", "Digital Tool Works (MIT)"),
            new PortProperties (1352, Protocol.TcpOrUdp, "lotusnote", "", "Lotus Note"),
            new PortProperties (1353, Protocol.TcpOrUdp, "relief", "", "Relief Consulting"),
            new PortProperties (1354, Protocol.TcpOrUdp, "rightbrain", "", "RightBrain Software"),
            new PortProperties (1355, Protocol.TcpOrUdp, "intuitive edge", "", "Intuitive Edge"),
            new PortProperties (1356, Protocol.TcpOrUdp, "cuillamartin", "", "CuillaMartin Company"),
            new PortProperties (1357, Protocol.TcpOrUdp, "pegboard", "", "Electronic PegBoard"),
            new PortProperties (1358, Protocol.TcpOrUdp, "connlcli", "", "CONNLCLI"),
            new PortProperties (1359, Protocol.TcpOrUdp, "ftsrv", "", "FTSRV"),
            new PortProperties (1360, Protocol.TcpOrUdp, "mimer", "", "MIMER"),
            new PortProperties (1361, Protocol.TcpOrUdp, "linx", "", "LinX"),
            new PortProperties (1362, Protocol.TcpOrUdp, "timeflies", "", "TimeFlies"),
            new PortProperties (1363, Protocol.TcpOrUdp, "ndm-requester", "", "Network DataMover Requester"),
            new PortProperties (1364, Protocol.TcpOrUdp, "ndm-server", "", "Network DataMover Server"),
            new PortProperties (1365, Protocol.TcpOrUdp, "adapt-sna", "", "Network Software Associates"),
            new PortProperties (1366, Protocol.TcpOrUdp, "netware-csp", "", "Novell NetWare Comm Service Platform"),
            new PortProperties (1367, Protocol.TcpOrUdp, "dcs", "", "DCS"),
            new PortProperties (1368, Protocol.TcpOrUdp, "screencast", "", "ScreenCast"),
            new PortProperties (1369, Protocol.TcpOrUdp, "gv-us", "", "GlobalView to Unix Shell"),
            new PortProperties (1370, Protocol.TcpOrUdp, "us-gv", "", "Unix Shell to GlobalView"),
            new PortProperties (1371, Protocol.TcpOrUdp, "fc-cli", "", "Fujitsu Config Protocol"),
            new PortProperties (1372, Protocol.TcpOrUdp, "fc-ser", "", "Fujitsu Config Protocol"),
            new PortProperties (1373, Protocol.TcpOrUdp, "chromagrafx", "", "Chromagrafx"),
            new PortProperties (1374, Protocol.TcpOrUdp, "molly", "", "EPI Software Systems"),
            new PortProperties (1375, Protocol.TcpOrUdp, "bytex", "", "Bytex"),
            new PortProperties (1376, Protocol.TcpOrUdp, "ibm-pps", "", "IBM Person to Person Software"),
            new PortProperties (1377, Protocol.TcpOrUdp, "cichlid", "", "Cichlid License Manager"),
            new PortProperties (1378, Protocol.TcpOrUdp, "elan", "", "Elan License Manager"),
            new PortProperties (1379, Protocol.TcpOrUdp, "dbreporter", "", "Integrity Solutions"),
            new PortProperties (1380, Protocol.TcpOrUdp, "telesis-licman", "", "Telesis Network License Manager"),
            new PortProperties (1381, Protocol.TcpOrUdp, "apple-licman", "", "Apple Network License Manager"),
            new PortProperties (1382, Protocol.TcpOrUdp, "udt_os"),
            new PortProperties (1383, Protocol.TcpOrUdp, "gwha", "", "GW Hannaway Network License Manager"),
            new PortProperties (1384, Protocol.TcpOrUdp, "os-licman", "", "Objective Solutions License Manager"),
            new PortProperties (1385, Protocol.TcpOrUdp, "atex_elmd", "", "Atex Publishing License Manager"),
            new PortProperties (1386, Protocol.TcpOrUdp, "checksum", "", "CheckSum License Manager"),
            new PortProperties (1387, Protocol.TcpOrUdp, "cadsi-lm", "", "Computer Aided Design Software Inc LM"),
            new PortProperties (1388, Protocol.TcpOrUdp, "objective-dbc", "", "Objective Solutions DataBase Cache"),
            new PortProperties (1389, Protocol.TcpOrUdp, "iclpv-dm", "", "Document Manager"),
            new PortProperties (1390, Protocol.TcpOrUdp, "iclpv-sc", "", "Storage Controller"),
            new PortProperties (1391, Protocol.TcpOrUdp, "iclpv-sas", "", "Storage Access Server"),
            new PortProperties (1392, Protocol.TcpOrUdp, "iclpv-pm", "", "Print Manager"),
            new PortProperties (1393, Protocol.TcpOrUdp, "iclpv-nls", "", "Network Log Server"),
            new PortProperties (1394, Protocol.TcpOrUdp, "iclpv-nlc", "", "Network Log Client"),
            new PortProperties (1395, Protocol.TcpOrUdp, "iclpv-wsm", "", "PC Workstation Manager software"),
            new PortProperties (1396, Protocol.TcpOrUdp, "dvl-activemail", "", "DVL Active Mail"),
            new PortProperties (1397, Protocol.TcpOrUdp, "audio-activmail", "", "Audio Active Mail"),
            new PortProperties (1398, Protocol.TcpOrUdp, "video-activmail", "", "Video Active Mail"),
            new PortProperties (1399, Protocol.TcpOrUdp, "cadkey-licman", "", "Cadkey License Manager"),
            new PortProperties (1400, Protocol.TcpOrUdp, "cadkey-tablet", "", "Cadkey Tablet Daemon"),
            new PortProperties (1401, Protocol.TcpOrUdp, "goldleaf-licman", "", "Goldleaf License Manager"),
            new PortProperties (1402, Protocol.TcpOrUdp, "prm-sm-np", "", "Prospero Resource Manager"),
            new PortProperties (1403, Protocol.TcpOrUdp, "prm-nm-np", "", "Prospero Resource Manager"),
            new PortProperties (1404, Protocol.TcpOrUdp, "igi-lm", "", "Infinite Graphics License Manager"),
            new PortProperties (1405, Protocol.TcpOrUdp, "ibm-res", "", "IBM Remote Execution Starter"),
            new PortProperties (1406, Protocol.TcpOrUdp, "netlabs-lm", "", "NetLabs License Manager"),
            new PortProperties (1407, Protocol.TcpOrUdp, "dbsa-lm", "", "DBSA License Manager"),
            new PortProperties (1408, Protocol.TcpOrUdp, "sophia-lm", "", "Sophia License Manager"),
            new PortProperties (1409, Protocol.TcpOrUdp, "here-lm", "", "Here License Manager"),
            new PortProperties (1410, Protocol.TcpOrUdp, "hiq", "", "HiQ License Manager"),
            new PortProperties (1411, Protocol.TcpOrUdp, "af", "", "AudioFile, RemoteVideoServer", "RemoteVideoServer: Overflow on connect"),
            new PortProperties (1412, Protocol.TcpOrUdp, "innosys", "", "InnoSys"),
            new PortProperties (1413, Protocol.TcpOrUdp, "innosys-acl", "", "Innosys-ACL"),
            new PortProperties (1414, Protocol.TcpOrUdp, "ibm-mqseries", "", "IBM MQSeries"),
            new PortProperties (1415, Protocol.TcpOrUdp, "dbstar", "", "DBStar"),
            new PortProperties (1416, Protocol.TcpOrUdp, "novell-lu6.2", "", "Novell LU6.2"),
            new PortProperties (1417, Protocol.TcpOrUdp, "timbuktu-srv1", "", "Timbuktu Service 1 Port"),
            new PortProperties (1418, Protocol.TcpOrUdp, "timbuktu-srv2", "", "Timbuktu Service 2 Port"),
            new PortProperties (1419, Protocol.TcpOrUdp, "timbuktu-srv3", "", "Timbuktu Service 3 Port"),
            new PortProperties (1420, Protocol.TcpOrUdp, "timbuktu-srv4", "", "Timbuktu Service 4 Port"),
            new PortProperties (1421, Protocol.TcpOrUdp, "gandalf-lm", "", "Gandalf License Manager"),
            new PortProperties (1422, Protocol.TcpOrUdp, "autodesk-lm", "", "Autodesk License Manager"),
            new PortProperties (1423, Protocol.TcpOrUdp, "essbase", "", "Essbase Arbor Software"),
            new PortProperties (1424, Protocol.TcpOrUdp, "hybrid", "", "Hybrid Encryption Protocol"),
            new PortProperties (1425, Protocol.TcpOrUdp, "zion-lm", "", "Zion Software License Manager"),
            new PortProperties (1426, Protocol.TcpOrUdp, "sas-1", "", "Satellite-data Acquisition System 1"),
            new PortProperties (1427, Protocol.TcpOrUdp, "mloadd", "", "mloadd monitoring tool"),
            new PortProperties (1428, Protocol.TcpOrUdp, "informatik-lm", "", "Informatik License Manager"),
            new PortProperties (1429, Protocol.TcpOrUdp, "nms", "", "Hypercom NMS"),
            new PortProperties (1430, Protocol.TcpOrUdp, "tpdu", "", "Hypercom TPDU"),
            new PortProperties (1431, Protocol.TcpOrUdp, "rgtp", "", "Reverse Gosip Transport"),
            new PortProperties (1432, Protocol.TcpOrUdp, "blueberry-lm", "", "Blueberry Software License Manager"),
            new PortProperties (1433, Protocol.TcpOrUdp, "ms-sql-s", "", "Microsoft-SQL-Server"),
            new PortProperties (1434, Protocol.TcpOrUdp, "ms-sql-m", "", "Microsoft-SQL-Monitor"),
            new PortProperties (1435, Protocol.TcpOrUdp, "ibm-cics", "", "IBM CISC"),
            new PortProperties (1436, Protocol.TcpOrUdp, "sas-2", "", "Satellite-data Acquisition System 2"),
            new PortProperties (1437, Protocol.TcpOrUdp, "tabula", "", "Tabula"),
            new PortProperties (1438, Protocol.TcpOrUdp, "eicon-server", "", "Eicon Security Agent/Server"),
            new PortProperties (1439, Protocol.TcpOrUdp, "eicon-x25", "", "Eicon X25/SNA Gateway"),
            new PortProperties (1440, Protocol.TcpOrUdp, "eicon-slp", "", "Eicon Service Location Protocol"),
            new PortProperties (1441, Protocol.TcpOrUdp, "cadis-1", "", "Cadis License Management"),
            new PortProperties (1442, Protocol.TcpOrUdp, "cadis-2", "", "Cadis License Management"),
            new PortProperties (1443, Protocol.TcpOrUdp, "ies-lm", "", "Integrated Engineering Software"),
            new PortProperties (1444, Protocol.TcpOrUdp, "marcam-lm", "", "Marcam  License Management"),
            new PortProperties (1445, Protocol.TcpOrUdp, "proxima-lm", "", "Proxima License Manager"),
            new PortProperties (1446, Protocol.TcpOrUdp, "ora-lm", "", "Optical Research Associates License Manager"),
            new PortProperties (1447, Protocol.TcpOrUdp, "apri-lm", "", "Applied Parallel Research LM"),
            new PortProperties (1448, Protocol.TcpOrUdp, "oc-lm", "", "OpenConnect License Manager"),
            new PortProperties (1449, Protocol.TcpOrUdp, "peport", "", "PEport"),
            new PortProperties (1450, Protocol.TcpOrUdp, "dwf", "", "Tandem Distributed Workbench Facility"),
            new PortProperties (1451, Protocol.TcpOrUdp, "infoman", "", "IBM Information Management"),
            new PortProperties (1452, Protocol.TcpOrUdp, "gtegsc-lm", "", "GTE Government Systems License Man"),
            new PortProperties (1453, Protocol.TcpOrUdp, "genie-lm", "", "Genie License Manager"),
            new PortProperties (1454, Protocol.TcpOrUdp, "interhdl_elmd", "", "interHDL License Manager"),
            new PortProperties (1455, Protocol.TcpOrUdp, "esl-lm", "", "ESL License Manager"),
            new PortProperties (1456, Protocol.TcpOrUdp, "dca", "", "DCA"),
            new PortProperties (1457, Protocol.TcpOrUdp, "valisys-lm", "", "Valisys License Manager"),
            new PortProperties (1458, Protocol.TcpOrUdp, "nrcabq-lm", "", "Nichols Research Corp."),
            new PortProperties (1459, Protocol.TcpOrUdp, "proshare1", "", "Proshare Notebook Application"),
            new PortProperties (1460, Protocol.TcpOrUdp, "proshare2", "", "Proshare Notebook Application"),
            new PortProperties (1461, Protocol.TcpOrUdp, "ibm_wrless_lan", "", "IBM Wireless LAN"),
            new PortProperties (1462, Protocol.TcpOrUdp, "world-lm", "", "World License Manager"),
            new PortProperties (1463, Protocol.TcpOrUdp, "nucleus", "", "Nucleus"),
            new PortProperties (1464, Protocol.TcpOrUdp, "msl_lmd", "", "MSL License Manager"),
            new PortProperties (1465, Protocol.TcpOrUdp, "pipes", "", "Pipes Platform"),
            new PortProperties (1466, Protocol.TcpOrUdp, "oceansoft-lm", "", "Ocean Software License Manager"),
            new PortProperties (1467, Protocol.TcpOrUdp, "csdmbase", "", "CSDMBASE"),
            new PortProperties (1468, Protocol.TcpOrUdp, "csdm", "", "CSDM"),
            new PortProperties (1469, Protocol.TcpOrUdp, "aal-lm", "", "Active Analysis Limited License Manager"),
            new PortProperties (1470, Protocol.TcpOrUdp, "uaiact", "", "Universal Analytics"),
            new PortProperties (1471, Protocol.TcpOrUdp, "csdmbase", "", "csdmbase"),
            new PortProperties (1472, Protocol.TcpOrUdp, "csdm", "", "csdm"),
            new PortProperties (1473, Protocol.TcpOrUdp, "openmath", "", "OpenMath"),
            new PortProperties (1474, Protocol.TcpOrUdp, "telefinder", "", "Telefinder"),
            new PortProperties (1475, Protocol.TcpOrUdp, "taligent-lm", "", "Taligent License Manager"),
            new PortProperties (1476, Protocol.TcpOrUdp, "clvm-cfg", "", "clvm-cfg"),
            new PortProperties (1477, Protocol.TcpOrUdp, "ms-sna-server", "", "ms-sna-server"),
            new PortProperties (1478, Protocol.TcpOrUdp, "ms-sna-base", "", "ms-sna-base"),
            new PortProperties (1479, Protocol.TcpOrUdp, "dberegister", "", "dberegister"),
            new PortProperties (1480, Protocol.TcpOrUdp, "pacerforum", "", "PacerForum"),
            new PortProperties (1481, Protocol.TcpOrUdp, "airs", "", "AIRS"),
            new PortProperties (1482, Protocol.TcpOrUdp, "miteksys-lm", "", "Miteksys License Manager"),
            new PortProperties (1483, Protocol.TcpOrUdp, "afs", "", "AFS License Manager"),
            new PortProperties (1484, Protocol.TcpOrUdp, "confluent", "", "Confluent License Manager"),
            new PortProperties (1485, Protocol.TcpOrUdp, "lansource", "", "LANSource"),
            new PortProperties (1486, Protocol.TcpOrUdp, "nms_topo_serv", "", "nms_topo_serv"),
            new PortProperties (1487, Protocol.TcpOrUdp, "localinfosrvr", "", "LocalInfoSrvr"),
            new PortProperties (1488, Protocol.TcpOrUdp, "docstor", "", "DocStor"),
            new PortProperties (1489, Protocol.TcpOrUdp, "dmdocbroker", "", "dmdocbroker"),
            new PortProperties (1490, Protocol.TcpOrUdp, "insitu-conf", "", "insitu-conf"),
            new PortProperties (1491, Protocol.TcpOrUdp, "anynetgateway", "", "anynetgateway"),
            new PortProperties (1492, Protocol.TcpOrUdp, "stone-design-1", "", "stone-design-1"),
            new PortProperties (1493, Protocol.TcpOrUdp, "netmap_lm", "", "netmap_lm"),
            new PortProperties (1494, Protocol.TcpOrUdp, "ica", "", "ica"),
            new PortProperties (1495, Protocol.TcpOrUdp, "cvc", "", "cvc"),
            new PortProperties (1496, Protocol.TcpOrUdp, "liberty-lm", "", "liberty-lm"),
            new PortProperties (1497, Protocol.TcpOrUdp, "rfx-lm", "", "rfx-lm"),
            new PortProperties (1498, Protocol.TcpOrUdp, "watcom-sql", "", "Watcom-SQL"),
            new PortProperties (1499, Protocol.TcpOrUdp, "fhc", "", "Federico Heinz Consultora"),
            new PortProperties (1500, Protocol.TcpOrUdp, "vlsi-lm", "", "VLSI License Manager, RemoteVideoServer", "RemoteVideoServer: Overflow on connect"),
            new PortProperties (1501, Protocol.TcpOrUdp, "sas-3", "", "Satellite-data Acquisition System 3"),
            new PortProperties (1502, Protocol.TcpOrUdp, "shivadiscovery", "", "Shiva"),
            new PortProperties (1503, Protocol.TcpOrUdp, "imtc-mcs", "", "Databeam"),
            new PortProperties (1504, Protocol.TcpOrUdp, "evb-elm", "", "EVB Software Engineering License Manager"),
            new PortProperties (1505, Protocol.TcpOrUdp, "funkproxy", "", "Funk Software, Inc."),
            new PortProperties (1513, Protocol.TcpOrUdp, "fujitsu-dtc"),
            new PortProperties (1514, Protocol.TcpOrUdp, "fujitsu-dtcns"),
            new PortProperties (1524, Protocol.TcpOrUdp, "ingreslock", "", "ingres"),
            new PortProperties (1525, Protocol.TcpOrUdp, "orasrv", "", "oracle"),
            new PortProperties (1525, Protocol.TcpOrUdp, "prospero-np", "", "Prospero Directory Service non-priv"),
            new PortProperties (1526, Protocol.TcpOrUdp, "pdap-np", "", "Prospero Data Access Prot non-priv"),
            new PortProperties (1527, Protocol.TcpOrUdp, "tlisrv", "", "oracle"),
            new PortProperties (1529, Protocol.TcpOrUdp, "coauthor", "", "oracle"),
            new PortProperties (1600, Protocol.TcpOrUdp, "issd"),
            new PortProperties (1650, Protocol.TcpOrUdp, "nkd"),
            new PortProperties (1651, Protocol.TcpOrUdp, "proshareaudio", "", "proshare conf audio"),
            new PortProperties (1652, Protocol.TcpOrUdp, "prosharevideo", "", "proshare conf video"),
            new PortProperties (1653, Protocol.TcpOrUdp, "prosharedata", "", "proshare conf data"),
            new PortProperties (1654, Protocol.TcpOrUdp, "prosharerequest", "", "proshare conf request"),
            new PortProperties (1655, Protocol.TcpOrUdp, "prosharenotify", "", "proshare conf notify"),
            new PortProperties (1661, Protocol.TcpOrUdp, "netview-aix-1", "", "netview-aix-1"),
            new PortProperties (1662, Protocol.TcpOrUdp, "netview-aix-2", "", "netview-aix-2"),
            new PortProperties (1663, Protocol.TcpOrUdp, "netview-aix-3", "", "netview-aix-3"),
            new PortProperties (1664, Protocol.TcpOrUdp, "netview-aix-4", "", "netview-aix-4"),
            new PortProperties (1665, Protocol.TcpOrUdp, "netview-aix-5", "", "netview-aix-5"),
            new PortProperties (1666, Protocol.TcpOrUdp, "netview-aix-6", "", "netview-aix-6"),
            new PortProperties (1986, Protocol.TcpOrUdp, "licensedaemon", "", "cisco license management"),
            new PortProperties (1987, Protocol.TcpOrUdp, "tr-rsrb-p1", "", "cisco RSRB Priority 1 port"),
            new PortProperties (1988, Protocol.TcpOrUdp, "tr-rsrb-p2", "", "cisco RSRB Priority 2 port"),
            new PortProperties (1989, Protocol.TcpOrUdp, "tr-rsrb-p3", "", "cisco RSRB Priority 3 port"),
            new PortProperties (1989, Protocol.TcpOrUdp, "mshnet", "", "MHSnet system"),
            new PortProperties (1990, Protocol.TcpOrUdp, "stun-p1", "", "cisco STUN Priority 1 port"),
            new PortProperties (1991, Protocol.TcpOrUdp, "stun-p2", "", "cisco STUN Priority 2 port"),
            new PortProperties (1992, Protocol.TcpOrUdp, "stun-p3", "", "cisco STUN Priority 3 port"),
            new PortProperties (1992, Protocol.TcpOrUdp, "ipsendmsg", "", "IPsendmsg"),
            new PortProperties (1993, Protocol.TcpOrUdp, "snmp-tcp-port", "", "cisco SNMP TCP port"),
            new PortProperties (1994, Protocol.TcpOrUdp, "stun-port", "", "cisco serial tunnel port"),
            new PortProperties (1995, Protocol.TcpOrUdp, "perf-port", "", "cisco perf port"),
            new PortProperties (1996, Protocol.TcpOrUdp, "tr-rsrb-port", "", "cisco Remote SRB port"),
            new PortProperties (1997, Protocol.TcpOrUdp, "gdp-port", "", "cisco Gateway Discovery Protocol"),
            new PortProperties (1998, Protocol.TcpOrUdp, "x25-svc-port", "", "cisco X.service (XOT)"),
            new PortProperties (1999, Protocol.TcpOrUdp, "tcp-id-port", "", "cisco identification port"),
            new PortProperties (2000, Protocol.TcpOrUdp, "callbook"),
            new PortProperties (2001, Protocol.Tcp, "dc"),
            new PortProperties (2001, Protocol.Udp, "wizard", "", "curry"),
            new PortProperties (2002, Protocol.TcpOrUdp, "globe"),
            new PortProperties (2004, Protocol.Tcp, "mailbox"),
            new PortProperties (2004, Protocol.Udp, "emce", "", "CCWS mm conf"),
            new PortProperties (2005, Protocol.Tcp, "berknet"),
            new PortProperties (2005, Protocol.Udp, "oracle"),
            new PortProperties (2006, Protocol.Tcp, "invokator"),
            new PortProperties (2006, Protocol.Udp, "raid-cc", "", "raid"),
            new PortProperties (2007, Protocol.Tcp, "dectalk"),
            new PortProperties (2007, Protocol.Udp, "raid-am"),
            new PortProperties (2008, Protocol.Tcp, "conf"),
            new PortProperties (2008, Protocol.Udp, "terminaldb"),
            new PortProperties (2009, Protocol.Tcp, "news"),
            new PortProperties (2009, Protocol.Udp, "whosockami"),
            new PortProperties (2010, Protocol.Tcp, "search"),
            new PortProperties (2010, Protocol.Udp, "pipe_server"),
            new PortProperties (2011, Protocol.Tcp, "raid-cc", "", "raid"),
            new PortProperties (2011, Protocol.Udp, "servserv"),
            new PortProperties (2012, Protocol.Tcp, "ttyinfo"),
            new PortProperties (2012, Protocol.Udp, "raid-ac"),
            new PortProperties (2013, Protocol.Tcp, "raid-am"),
            new PortProperties (2013, Protocol.Udp, "raid-cd"),
            new PortProperties (2014, Protocol.Tcp, "troff"),
            new PortProperties (2014, Protocol.Udp, "raid-sf"),
            new PortProperties (2015, Protocol.Tcp, "cypress"),
            new PortProperties (2015, Protocol.Udp, "raid-cs"),
            new PortProperties (2016, Protocol.TcpOrUdp, "bootserver"),
            new PortProperties (2017, Protocol.Tcp, "cypress-stat"),
            new PortProperties (2017, Protocol.Udp, "bootclient"),
            new PortProperties (2018, Protocol.Tcp, "terminaldb"),
            new PortProperties (2018, Protocol.Udp, "rellpack"),
            new PortProperties (2019, Protocol.Tcp, "whosockami"),
            new PortProperties (2019, Protocol.Udp, "about"),
            new PortProperties (2020, Protocol.TcpOrUdp, "xinupageserver"),
            new PortProperties (2021, Protocol.Tcp, "servexec"),
            new PortProperties (2021, Protocol.Udp, "xinuexpansion1"),
            new PortProperties (2022, Protocol.Tcp, "down"),
            new PortProperties (2022, Protocol.Udp, "xinuexpansion2"),
            new PortProperties (2023, Protocol.TcpOrUdp, "xinuexpansion3"),
            new PortProperties (2024, Protocol.TcpOrUdp, "xinuexpansion4"),
            new PortProperties (2025, Protocol.Tcp, "ellpack"),
            new PortProperties (2025, Protocol.Udp, "xribs"),
            new PortProperties (2026, Protocol.TcpOrUdp, "scrabble"),
            new PortProperties (2027, Protocol.TcpOrUdp, "shadowserver"),
            new PortProperties (2028, Protocol.TcpOrUdp, "submitserver"),
            new PortProperties (2030, Protocol.TcpOrUdp, "device2"),
            new PortProperties (2032, Protocol.TcpOrUdp, "blackboard"),
            new PortProperties (2033, Protocol.TcpOrUdp, "glogger"),
            new PortProperties (2034, Protocol.TcpOrUdp, "scoremgr"),
            new PortProperties (2035, Protocol.TcpOrUdp, "imsldoc"),
            new PortProperties (2038, Protocol.TcpOrUdp, "objectmanager"),
            new PortProperties (2040, Protocol.TcpOrUdp, "lam"),
            new PortProperties (2041, Protocol.TcpOrUdp, "interbase"),
            new PortProperties (2042, Protocol.TcpOrUdp, "isis"),
            new PortProperties (2043, Protocol.TcpOrUdp, "isis-bcast"),
            new PortProperties (2044, Protocol.TcpOrUdp, "rimsl"),
            new PortProperties (2045, Protocol.TcpOrUdp, "cdfunc"),
            new PortProperties (2046, Protocol.TcpOrUdp, "sdfunc"),
            new PortProperties (2047, Protocol.TcpOrUdp, "dls"),
            new PortProperties (2048, Protocol.TcpOrUdp, "dls-monitor"),
            new PortProperties (2049, Protocol.TcpOrUdp, "shilp"),
            new PortProperties (2065, Protocol.TcpOrUdp, "dlsrpn", "", "Data Link Switch Read Port Number"),
            new PortProperties (2067, Protocol.TcpOrUdp, "dlswpn", "", "Data Link Switch Write Port Number"),
            new PortProperties (2201, Protocol.TcpOrUdp, "ats", "", "Advanced Training System Program"),
            new PortProperties (2500, Protocol.TcpOrUdp, "rtsserv", "", "Resource Tracking system server"),
            new PortProperties (2501, Protocol.TcpOrUdp, "rtsclient", "", "Resource Tracking system client"),
            new PortProperties (2564, Protocol.Tcp, "hp-3000-telnet", "", "HP 3NS/VT block mode telnet"),
            new PortProperties (2784, Protocol.TcpOrUdp, "www-dev", "", "world wide web - development"),
            new PortProperties (3049, Protocol.TcpOrUdp, "NSWS"),
            new PortProperties (3264, Protocol.TcpOrUdp, "ccmail", "", "cc:mail/lotus"),
            new PortProperties (3333, Protocol.TcpOrUdp, "dec-notes", "", "DEC Notes"),
            new PortProperties (3984, Protocol.TcpOrUdp, "mapper-nodemgr", "", "MAPPER network node manager"),
            new PortProperties (3985, Protocol.TcpOrUdp, "mapper-mapethd", "", "MAPPER TCP/IP server"),
            new PortProperties (3986, Protocol.TcpOrUdp, "mapper-ws_ethd", "", "MAPPER workstation server"),
            new PortProperties (3421, Protocol.TcpOrUdp, "bmap", "", "Bull Apprise portmapper"),
            new PortProperties (3900, Protocol.TcpOrUdp, "udt_os", "", "Unidata UDT OS"),
            new PortProperties (4132, Protocol.TcpOrUdp, "nuts_dem", "", "NUTS Daemon"),
            new PortProperties (4133, Protocol.TcpOrUdp, "nuts_bootp", "", "NUTS Bootp Server"),
            new PortProperties (4343, Protocol.TcpOrUdp, "unicall", "", "UNICALL"),
            new PortProperties (4444, Protocol.TcpOrUdp, "krb524", "", "KRB524"),
            new PortProperties (4672, Protocol.TcpOrUdp, "rfa", "", "remote file access server"),
            new PortProperties (5000, Protocol.TcpOrUdp, "commplex-main"),
            new PortProperties (5001, Protocol.TcpOrUdp, "commplex-link"),
            new PortProperties (5002, Protocol.TcpOrUdp, "rfe", "", "radio free ethernet"),
            new PortProperties (5010, Protocol.TcpOrUdp, "telelpathstart", "", "TelepathStart"),
            new PortProperties (5011, Protocol.TcpOrUdp, "telelpathattack", "", "TelepathAttack"),
            new PortProperties (5050, Protocol.TcpOrUdp, "mmcc", "", "multimedia conference control tool"),
            new PortProperties (5145, Protocol.TcpOrUdp, "rmonitor_secure"),
            new PortProperties (5190, Protocol.TcpOrUdp, "aol", "", "America-Online"),
            new PortProperties (5236, Protocol.TcpOrUdp, "padl2sim"),
            new PortProperties (5300, Protocol.TcpOrUdp, "hacl-hb", "", "# HA cluster heartbeat"),
            new PortProperties (5301, Protocol.TcpOrUdp, "hacl-gs", "", "# HA cluster general services"),
            new PortProperties (5302, Protocol.TcpOrUdp, "hacl-cfg", "", "# HA cluster configuration"),
            new PortProperties (5303, Protocol.TcpOrUdp, "hacl-probe", "", "# HA cluster probing"),
            new PortProperties (5304, Protocol.TcpOrUdp, "hacl-local"),
            new PortProperties (5305, Protocol.TcpOrUdp, "hacl-test"),
            new PortProperties (6000, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6001, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6002, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6003, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6004, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6005, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6006, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6007, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6008, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6009, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6010, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6011, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6012, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6013, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6014, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6015, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6016, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6017, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6018, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6019, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6020, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6021, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6022, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6023, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6024, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6025, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6026, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6027, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6028, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6029, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6030, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6031, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6032, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6033, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6034, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6035, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6036, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6037, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6038, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6039, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6040, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6041, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6042, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6043, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6044, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6045, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6046, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6047, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6048, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6049, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6050, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6051, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6052, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6053, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6054, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6055, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6056, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6057, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6058, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6059, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6060, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6061, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6062, Protocol.TcpOrUdp, "x11", "", "X Window System"),
            new PortProperties (6111, Protocol.TcpOrUdp, "sub-process", "", "HP SoftBench Sub-Process Control"),
            new PortProperties (6141, Protocol.TcpOrUdp, "meta-corp", "", "Meta Corporation License Manager"),
            new PortProperties (6142, Protocol.TcpOrUdp, "aspentec-lm", "", "Aspen Technology License Manager"),
            new PortProperties (6143, Protocol.TcpOrUdp, "watershed-lm", "", "Watershed License Manager"),
            new PortProperties (6144, Protocol.TcpOrUdp, "statsci1-lm", "", "StatSci License Manager - 1"),
            new PortProperties (6145, Protocol.TcpOrUdp, "statsci2-lm", "", "StatSci License Manager - 2"),
            new PortProperties (6146, Protocol.TcpOrUdp, "lonewolf-lm", "", "Lone Wolf Systems License Manager"),
            new PortProperties (6147, Protocol.TcpOrUdp, "montage-lm", "", "Montage License Manager"),
            new PortProperties (6558, Protocol.TcpOrUdp, "xdsxdm"),
            new PortProperties (7000, Protocol.TcpOrUdp, "afs3-fileserver", "", "file server itself"),
            new PortProperties (7001, Protocol.TcpOrUdp, "afs3-callback", "", "callbacks to cache managers"),
            new PortProperties (7002, Protocol.TcpOrUdp, "afs3-prserver", "", "users & groups database"),
            new PortProperties (7003, Protocol.TcpOrUdp, "afs3-vlserver", "", "volume location database"),
            new PortProperties (7004, Protocol.TcpOrUdp, "afs3-kaserver", "", "AFS/Kerberos authentication service"),
            new PortProperties (7005, Protocol.TcpOrUdp, "afs3-volser", "", "volume managment server"),
            new PortProperties (7006, Protocol.TcpOrUdp, "afs3-errors", "", "error interpretation service"),
            new PortProperties (7007, Protocol.TcpOrUdp, "afs3-bos", "", "basic overseer process"),
            new PortProperties (7008, Protocol.TcpOrUdp, "afs3-update", "", "server-to-server updater"),
            new PortProperties (7009, Protocol.TcpOrUdp, "afs3-rmtsys", "", "remote cache manager service"),
            new PortProperties (7010, Protocol.TcpOrUdp, "ups-onlinet", "", "onlinet uninterruptable power supplies"),
            new PortProperties (7100, Protocol.TcpOrUdp, "font-service", "", "X Font Service"),
            new PortProperties (7200, Protocol.TcpOrUdp, "fodms", "", "FODMS FLIP"),
            new PortProperties (9535, Protocol.TcpOrUdp, "man"),
            new PortProperties (17007, Protocol.TcpOrUdp, "isode-dua")
        };

        public PortProperties GetPortProperties(int portNumber)
        {
            var result = WellKnownPorts.FirstOrDefault(port => port.PortNumber == portNumber);
            return result ?? new PortProperties(portNumber, Protocol.Unknown, String.Empty);
        }
    }
}