namespace Enums
{
	public enum SentinelSuperProHardwareKeyDataType
	{
		Undefined,
		SafeNet,
		SafeNet_KeySerialNumber,
		SafeNet_DeveloperID,
		VSP_license,
		VSP_sendmail,
		VSP_unique_print,
		VSP_sziltech_server_number,
		VSP_sziltech_camera_number,
		VSP_other_server_number,
		VSP_other_camera_number,
		VSP_user_number,
		LV_licensed,
		LV_sziltech_server_number,
		LV_sziltech_camera_number,
		LV_other_server_number,
		LV_other_camera_number,
		LV_user_number,
		LV_edition,
		AlbertSubtype,
		AlbertSerial,
		AlbertProtocolVersion,
		AlbertGeneralLicense,
		AlbertCameraLicense,
		AlbertAudioLicense,
		AlbertLicensePlateRecognitionLicense,
		AlbertCameraControlLicense
	}
}
