namespace Enums
{
	public enum ServiceControlsAccepted : uint
	{
		SERVICE_ACCEPT_NETBINDCHANGE = 0x10,
		SERVICE_ACCEPT_PARAMCHANGE = 0x8,
		SERVICE_ACCEPT_PAUSE_CONTINUE = 0x2,
		SERVICE_ACCEPT_PRESHUTDOWN = 0x100,
		SERVICE_ACCEPT_ACCEPT_SHUTDOWN = 0x4,
		SERVICE_ACCEPT_STOP = 0x1,

		SERVICE_ACCEPT_HARDWAREPROFILECHANGE = 0x20,
		SERVICE_ACCEPT_POWEREVENT = 0x40,
		SERVICE_ACCEPT_SESSIONCHANGE = 0x80
	}
}
